spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/upi-yx-mg?useUnicode=true&characterEncoding=utf8
        driverClassName: com.mysql.jdbc.Driver
        username: upi-yx-mg
        password: dXBpLXl4LW1nMDk=
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        filters: stat,wall,log4j
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500